path = ["/home/gsus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin", "/home/gsus/.cargo/bin", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/sbin", "/var/lib/snapd/snap/bin", "/home/gsus/go/bin"]
prompt = "starship prompt"
skip_welcome_message = true
startup = ["mkdir ~/.cache/startup", "starship init nu | save ~/.cache/starship/init.nu", "source ~/.cache/starship/init.nu", "source ~/.config/nu/init.nu"]
table_mode = "light"

[env]
ALACRITTY_LOG = "/tmp/Alacritty-13234.log"
CMD_DURATION_MS = "13"
COLORTERM = "truecolor"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DESKTOP_SESSION = "i3"
GDMSESSION = "i3"
GDM_LANG = "en_US.UTF-8"
HOME = "/home/gsus"
I3SOCK = "/run/user/1000/i3/ipc-socket.5692"
LANG = "en_US.UTF-8"
LOGNAME = "gsus"
PWD = "/home/gsus"
SHELL = "/home/gsus/.cargo/bin/nu"
SHLVL = "0"
SSH_AGENT_PID = "5671"
SSH_AUTH_SOCK = "/tmp/ssh-XXXXXX96LHvF/agent.5648"
STARSHIP_SESSION_KEY = "LJLbt0DXnvAt4PQU"
STARSHIP_SHELL = "nu"
SYSTEMD_EXEC_PID = "5541"
TERM = "xterm-256color"
TMUX = "/tmp/tmux-1000/default,13246,0"
TMUX_PANE = "%0"
TMUX_PLUGIN_MANAGER_PATH = "/home/gsus/.tmux/plugins/"
USER = "gsus"
USERNAME = "gsus"
WINDOWID = "16777218"
WINDOWPATH = "4"
XAUTHORITY = "/run/user/1000/gdm/Xauthority"
XDG_CURRENT_DESKTOP = "i3"
XDG_DATA_DIRS = "/home/gsus/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SEAT = "seat0"
XDG_SESSION_CLASS = "user"
XDG_SESSION_DESKTOP = "i3"
XDG_SESSION_ID = "7"
XDG_SESSION_TYPE = "x11"
XDG_VTNR = "4"
_ = "/usr/bin/alacritty"

[line_editor]
edit_mode = "vi"
