#!/bin/bash



max_brightness=$(cat /sys/class/backlight/acpi_video0/max_brightness)
current_brightness=$(cat /sys/class/backlight/acpi_video0/brightness)
br=$(dc --expression "2k $max_brightness $current_brightness 100 /* 0k p")


echo -n "$($HOME/.config/xmobar/scripts/percentage $br        ) $br% "
