format = """
$directory\
$git_branch\
$git_status\
$package\
$rust$golang\
$cmd_duration\
$line_break\
$jobs\
$character"""

[directory]
style = "bold fg:6"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "fg:3"

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "bold red"

[package]
format = '[$symbol$version ]($style)'

[rust]
format = '[$symbol($version )]($style)'
