#!/bin/sh
# https://brianbuccola.com/how-to-install-xmonad-and-xmobar-via-stack/


stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"

# move the executable to `$HOME/.local/bin/xmonad`
# mv "$1" "$HOME/.local/bin/xmonad"
