
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/5.yaml

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib
- xmonad-themes
extra-deps:
  - iwlib-0.1.0
  - netlink-1.1.1.0
  - Cabal-3.2.1.0
  - directory-1.3.6.2
  - process-1.6.11.0
  - time-1.9.3
  - unix-2.7.2.2
  - transformers-0.5.6.2

flags:
  xmobar:
    all_extensions: true


